#!/usr/bin/env bash

# +--------+
# | System |
# +--------+

alias shutdown='sudo shutdown now'
alias restart='sudo reboot'
alias suspend='sudo pm-suspend'

# +----+
# | cd |
# +----+

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

# +------+
# | grep |
# +------+

alias grep='grep -P -i --color=auto'

# +------+
# | dust |
# +------+

alias dust='du -sh * | sort -hr'

# +-----+
# | git |
# +-----+

alias gc='git commit -m "Update"'

